const mockMovieData = [
  {
    id: 16,
    title: "Deadpool & Wolverine",
    year: 2016,
    rating: 7.5,
    quality: "HD",
    poster: "https://akcdn.detik.net.id/community/media/visual/2024/07/25/film-deadpool-wolverinefoto-marvel-studios.jpeg?w=620&q=90",
    genres: ["Action", "Comedy", "Superhero"],
    duration: 127,
    type: "Movie"
  },
  {
    id: 35,
    title: "Jujutsu Kaisen",
    year: 2020,
    rating: 8.6,
    quality: "HD",
    poster: "https://wallpapercave.com/wp/wp8936520.jpg",
    genres: ["Animation", "Action", "Fantasy"],
    duration: 23,
    seasons: 2,
    type: "TV Series"
  },
  {
    id: 5,
    title: "Spirited Away",
    year: 2001,
    rating: 8.6,
    quality: "HD",
    poster: "https://a.ltrbxd.com/resized/sm/upload/1g/fk/4g/3c/ynXoOxmDHNQ4UAy0oU6avW71HVW-0-230-0-345-crop.jpg?k=53d4d12e06",
    genres: ["Animation", "Fantasy", "Family"],
    duration: 125,
    type: "Movie"
  },
  {
    id: 37,
    title: "One Piece",
    year: 1999,
    rating: 9.0,
    quality: "HD",
    poster: "https://image.tmdb.org/t/p/original/4I1xjEKZxeeBT8RXg0BA6k6PM8e.jpg",
    genres: ["Animation", "Adventure", "Fantasy"],
    duration: 24,
    seasons: 20,
    type: "TV Series"
  },
  {
    id: 14,
    title: "Dune",
    year: 2021,
    rating: 8.1,
    quality: "HD",
    poster: "https://theculturednerd.org/wp-content/uploads/2020/12/Dune-Poster-695x1024.png",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    duration: 155,
    type: "Movie"
  },
  {
    id: 33,
    title: "Attack on Titan",
    year: 2013,
    rating: 9.0,
    quality: "HD",
    poster: "https://th.bing.com/th/id/R.c57babd22d0452a2696f6fe97e590951?rik=GDwRnHEZ7tMeOQ&pid=ImgRaw&r=0",
    genres: ["Animation", "Action", "Drama"],
    duration: 24,
    type: "TV Series"
  },
  {
    id: 18,
    title: "Mission Impossible: The Final Reckoning",
    year: 2025,
    rating: 8.3,
    quality: "CAM",
    poster: "https://tse1.mm.bing.net/th/id/OIP.y1ZRanTfkxyCFXT2jFs76AHaK5?rs=1&pid=ImgDetMain&o=7&rm=3",
    genres: ["Action", "Thriller", "Adventure"],
    duration: 150,
    type: "Movie"
  },
  {
    id: 34,
    title: "Game of Thrones",
    year: 2011,
    rating: 9.2,
    quality: "HD",
    poster: "https://tse3.mm.bing.net/th/id/OIP.yoko8aG1nVlr3zZq8xUNawHaLS?rs=1&pid=ImgDetMain&o=7&rm=3",
    genres: ["Drama", "Fantasy", "Adventure"],
    duration: 57,
    seasons: 8,
    type: "TV Series"
  },
  {
    id: 9,
    title: "Blade Runner 2049",
    year: 2017,
    rating: 8.0,
    quality: "HD",
    poster: "https://image.tmdb.org/t/p/original/muYiihFhXEpPcS2WltlSOgmOL0j.jpg",
    genres: ["Sci-Fi", "Drama", "Mystery"],
    duration: 164,
    type: "Movie"
  },
  {
    id: 23,
    title: "Vinland Saga",
    year: 2019,
    rating: 8.5,
    quality: "HD",
    poster: "https://www.themoviedb.org/t/p/original/AuUgiPuvwkBq20kagz4ZcyhkPTY.jpg",
    genres: ["Animation", "Action", "Drama"],
    duration: 120,
    type: "TV Series"
  },
  {
    id: 2,
    title: "KPop Demon Hunters",
    year: 2025,
    rating: 7.7,
    quality: "HD",
    poster: "https://media2.firstshowing.net/firstshowing/img17/Kpopdemonhuntsbigmainpost592.jpg",
    genres: ["Animation", "Action", "Fantasy"],
    duration: 105,
    type: "Movie"
  },
  {
    id: 27,
    title: "Grave of the Fireflies",
    year: 1988,
    rating: 8.5,
    quality: "HD",
    poster: "https://image.tmdb.org/t/p/original/fs9rvMCDCqZMr6AGciakP0Ds7og.jpg",
    genres: ["Animation", "Drama", "War"],
    duration: 89,
    type: "Movie"
  },
  {
    id: 12,
    title: "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
    year: 2025,
    rating: 8.8,
    quality: "CAM",
    poster: "https://cdn.oneesports.gg/cdn-data/2024/07/Anime_DemonSlayerMovieTrilogy_InfinityCastleArc_Poster.jpg",
    genres: ["Animation", "Action", "Fantasy"],
    duration: 130,
    type: "Movie"
  },
  {
    id: 6,
    title: "Interstellar",
    year: 2014,
    rating: 8.6,
    quality: "HD",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    duration: 169,
    type: "Movie"
  },
  {
    id: 36,
    title: "The Walking Dead",
    year: 2010,
    rating: 8.1,
    quality: "HD",
    poster: "https://comicvine.gamespot.com/a/uploads/scale_small/14/142800/3332217-430540-the_walking_dead_04.jpg",
    genres: ["Drama", "Horror", "Thriller"],
    duration: 45,
    seasons: 11,
    type: "TV Series"
  },
  {
    id: 21,
    title: "Avatar: The Way of Water",
    year: 2022,
    rating: 7.8,
    quality: "HD",
    poster: "https://static1.srcdn.com/wordpress/wp-content/uploads/2023/05/avater-the-way-of-water-poster.jpg",
    genres: ["Sci-Fi", "Adventure", "Action"],
    duration: 192,
    type: "Movie"
  },
  {
    id: 1,
    title: "How to Train Your Dragon",
    year: 2025,
    rating: 7.9,
    quality: "HD",
    poster: "https://imgix.hoyts.com.au/mx/posters/nz/how-to-train-your-dragon-20d2a983.jpg",
    genres: ["Animation", "Adventure", "Fantasy"],
    duration: 98,
    type: "Movie"
  },
  {
    id: 25,
    title: "Troy",
    year: 2004,
    rating: 7.3,
    quality: "HD",
    poster: "https://cdn-images-1.medium.com/max/1200/1*MTej8TejwS7fm9vbXlklRQ.jpeg",
    genres: ["War", "Action", "Drama"],
    duration: 163,
    type: "Movie"
  },
  {
    id: 31,
    title: "The Wild Robot",
    year: 2024,
    rating: 8.1,
    quality: "HD",
    poster: "https://image.tmdb.org/t/p/original/6GT9lvyyKx7hiwtKMC4BisMTA7N.jpg",
    genres: ["Animation", "Adventure", "Family"],
    duration: 102,
    type: "Movie"
  },
  {
    id: 19,
    title: "Tangled",
    year: 2010,
    rating: 7.7,
    quality: "HD",
    poster: "https://th.bing.com/th/id/R.2920e79776377270ebb9551daf6c89e1?rik=8IevnwmOnx26nA&riu=http%3a%2f%2f2.bp.blogspot.com%2f_Fxf2MsuHlys%2fTKU1cOa-zGI%2fAAAAAAAAAEk%2fPpS2EghmYo8%2fs1600%2fPoster%2bof%2bTangled.jpg&ehk=qzCCYtdnc05GVM7Y8VA0EM4iLxrXB9pJ9G1tmXBFwGw%3d&risl=&pid=ImgRaw&r=0",
    genres: ["Animation", "Romance", "Family"],
    duration: 100,
    type: "Movie"
  },
  {
    id: 3,
    title: "The Dark Knight",
    year: 2008,
    rating: 9.0,
    quality: "HD",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    genres: ["Action", "Crime", "Drama"],
    duration: 152,
    type: "Movie"
  },
  {
    id: 28,
    title: "My Neighbor Totoro",
    year: 1988,
    rating: 8.2,
    quality: "HD",
    poster: "https://i.pinimg.com/736x/f7/3e/ca/f73eca98ae27d6ae174c707f44c610bb.jpg",
    genres: ["Animation", "Fantasy", "Family"],
    duration: 86,
    type: "Movie"
  },
  {
    id: 7,
    title: "Guardians of the Galaxy",
    year: 2014,
    rating: 8.0,
    quality: "HD",
    poster: "https://tse2.mm.bing.net/th/id/OIP.39_RWIX2lm1Zvpp4BPN-5wHaLH?rs=1&pid=ImgDetMain&o=7&rm=3",
    genres: ["Action", "Comedy", "Sci-Fi"],
    duration: 121,
    type: "Movie"
  },
  {
    id: 32,
    title: "Coco",
    year: 2017,
    rating: 8.4,
    quality: "HD",
    poster: "https://th.bing.com/th/id/R.8a49e628a2097b061089d80dca533233?rik=3NcQ091UtOBp5Q&riu=http%3a%2f%2fwww.impawards.com%2f2017%2fposters%2fcoco_ver14.jpg&ehk=Wd2oDJK6NVToKF0ObiNvqYlUNHtU0N%2fwW5F0CTbE1co%3d&risl=&pid=ImgRaw&r=0",
    genres: ["Animation", "Family", "Fantasy"],
    duration: 105,
    type: "Movie"
  },
  {
    id: 10,
    title: "Fury",
    year: 2014,
    rating: 7.6,
    quality: "HD",
    poster: "https://www.themoviedb.org/t/p/original/ykWW3qvd9puwY0RHMP8G56LWUKU.jpg",
    genres: ["War", "Action", "Drama"],
    duration: 134,
    type: "Movie"
  },
  {
    id: 29,
    title: "Spider-Man: Into the Spider-Verse",
    year: 2018,
    rating: 8.4,
    quality: "HD",
    poster: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609769218i/56551172.jpg",
    genres: ["Animation", "Fantasy", "Adventure"],
    duration: 117,
    type: "Movie"
  },
  {
    id: 13,
    title: "Howl's Moving Castle",
    year: 2004,
    rating: 8.2,
    quality: "HD",
    poster: "https://tse2.mm.bing.net/th/id/OIP.d97EyMCON2iXzqGE1hmbZgHaLH?rs=1&pid=ImgDetMain&o=7&rm=3",
    genres: ["Animation", "Fantasy", "Romance"],
    duration: 119,
    type: "Movie"
  },
  {
    id: 11,
    title: "Wall-E",
    year: 2008,
    rating: 8.4,
    quality: "HD",
    poster: "https://www.lighthousecinema.ie/themes/user/site/lighthouse/images/walle_1_.webp",
    genres: ["Animation", "Adventure", "Sci-Fi"],
    duration: 98,
    type: "Movie"
  },
  {
    id: 20,
    title: "Suzume",
    year: 2022,
    rating: 7.6,
    quality: "HD",
    poster: "https://www.themoviedb.org/t/p/original/vIeu8WysZrTSFb2uhPViKjX9EcC.jpg",
    genres: ["Animation", "Adventure", "Fantasy"],
    duration: 122,
    type: "Movie"
  },
  {
    id: 8,
    title: "Avengers: Endgame",
    year: 2019,
    rating: 8.4,
    quality: "HD",
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    genres: ["Action", "Adventure", "Sci-Fi"],
    duration: 181,
    type: "Movie"
  },
  {
    id: 24,
    title: "Kingdom of Heaven",
    year: 2005,
    rating: 7.2,
    quality: "HD",
    poster: "https://tse3.mm.bing.net/th/id/OIP.ieM1ibTLmZ7jBvO2DtNmagHaLH?rs=1&pid=ImgDetMain&o=7&rm=3",
    genres: ["Drama", "War", "History"],
    duration: 144,
    type: "Movie"
  },
  {
    id: 4,
    title: "Ne Zha 2",
    year: 2025,
    rating: 8.1,
    quality: "HD",
    poster: "https://cdn.moviefone.com/image-assets/980477/cb5NyNrqiCNNoDkA8FfxHAtypdG.jpg?d=360x540&q=50",
    genres: ["Animation", "Fantasy", "Adventure"],
    duration: 118,
    type: "Movie"
  },
  {
    id: 26,
    title: "300: Rise of an Empire",
    year: 2014,
    rating: 6.2,
    quality: "HD",
    poster: "https://movieposters.ie/wp-content/uploads/2013/06/300-rise-empire-poster-811x1200.jpg",
    genres: ["Action", "War", "Fantasy"],
    duration: 102,
    type: "Movie"
  },
  {
    id: 15,
    title: "Ratatouille",
    year: 2007,
    rating: 8.0,
    quality: "HD",
    poster: "https://upload.wikimedia.org/wikipedia/en/5/50/RatatouillePoster.jpg",
    genres: ["Animation", "Comedy", "Family"],
    duration: 111,
    type: "Movie"
  },
  {
    id: 22,
    title: "Spy x Family: Code White",
    year: 2023,
    rating: 8.0,
    quality: "HD",
    poster: "https://inforadar.disway.id/upload/077769745c3cd3595cb9b085b085ffb6.jpeg",
    genres: ["Animation", "Action", "Comedy"],
    duration: 110,
    type: "Movie"
  },
  {
    id: 30,
    title: "Kung Fu Panda 4",
    year: 2025,
    rating: 7.8,
    quality: "CAM",
    poster: "https://tse1.mm.bing.net/th/id/OIP.wgje0tOcZ397qcpjuXWt7gHaLu?rs=1&pid=ImgDetMain&o=7&rm=3",
    genres: ["Animation", "Action", "Comedy"],
    duration: 100,
    type: "Movie"
  }
];